In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
df = pd.read_csv('../Data/preprocessed_movies_data.csv')
df.head()

,Title,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,gross_US_Canada,opening_weekend_Gross,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,nominations,oscars,Category
0,1. Star Wars: Episode III - Revenge of the Sith,2005,140.0,PG-13,7.6,867000.0,113000000.0,850035635.0,380270577.0,108435841.0,...,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action Epic, Adventure Epic, Dark Fantasy, Fan...","United States, Italy, Switzerland, Thailand, U...","Mount Etna, Catania, Sicily, Italy","Lucasfilm, Mestiere Cinema, Pandora Films",English,64,1,Epic
1,"2. The Chronicles of Narnia: The Lion, the Wit...",2005,143.0,PG,6.9,438000.0,180000000.0,745013115.0,291710957.0,65556312.0,...,"Ann Peacock, Andrew Adamson, Christopher Markus","Tilda Swinton, Georgie Henley, William Moseley","Fantasy Epic, Supernatural Fantasy, Sword & So...","United Kingdom, United States","Adrspach National Park, Trutnov, Czech Republic","Walt Disney Pictures, Walden Media","English, German, Brazilian Sign Language",46,0,Epic
2,3. Harry Potter and the Goblet of Fire,2005,157.0,PG-13,7.7,705000.0,150000000.0,897468952.0,290469928.0,102685961.0,...,"Steve Kloves, J.K. Rowling","Daniel Radcliffe, Emma Watson, Rupert Grint","Sword & Sorcery, Teen Adventure, Teen Fantasy,...","United Kingdom, United States","Glenfinnan Viaduct, Fort William, Highland, Sc...","Warner Bros., Heyday Films, Patalex Productions","English, French, Latin",48,1,Fantasy
3,4. War of the Worlds,2005,117.0,PG-13,6.5,485000.0,132000000.0,603873504.0,234280354.0,64878725.0,...,"Josh Friedman, David Koepp, H.G. Wells","Tom Cruise, Dakota Fanning, Tim Robbins","Action Epic, Adventure Epic, Alien Invasion, D...",United States,"JF Kennedy Blvd., Bayonne, New Jersey, USA","Paramount Pictures, Dreamworks Pictures, Ambli...",English,49,3,Epic
4,5. King Kong,2005,187.0,PG-13,7.2,455000.0,207000000.0,556906378.0,218080025.0,50130145.0,...,"Fran Walsh, Philippa Boyens, Peter Jackson","Naomi Watts, Jack Black, Adrien Brody","Adventure Epic, Dark Romance, Dinosaur Adventu...","United States, New Zealand, Germany","Shelly Bay, Wellington, New Zealand","Universal Pictures, WingNut Films, Big Primate...",English,104,0,Epic

In [13]:
# %pip install category_encoders

In [14]:
from category_encoders import TargetEncoder
from sklearn.preprocessing import LabelEncoder

df['Profit'] = df['grossWorldWide'] / df['budget']

enc = LabelEncoder()
df['Category'] = enc.fit_transform(df['Category'])
enc = LabelEncoder()
df['MPA'] = enc.fit_transform(df['MPA'])

te = TargetEncoder()
df['directors'] = te.fit_transform(df['directors'], df['Profit'])
te = TargetEncoder()
df['stars'] = te.fit_transform(df['stars'], df['Profit'])
te = TargetEncoder()
df['production_companies'] = te.fit_transform(df['production_companies'], df['Profit'])

df = df.drop(columns=['Languages', 'genres', 'countries_origin', 'filming_locations', 'writers'])

df.head()

KeyError: "['writer'] not found in axis"

In [10]:
df.to_csv('./Data/encoded_movies_data.csv', index=False)